apiVersion: apps/v1
kind: Deployment
metadata:
  name: carapp-deployment
  labels:
    app: carapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carapp
  template:
    metadata:
      labels:
        app: carapp 
    spec:
      containers:
      - name: carserver
        image: car-app:latest
        ports:
        - containerPort: 8081
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: carapp-service
spec:
  selector:
    app: carapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8081
    nodePort: 31110