apiVersion: apps/v1
kind: Deployment
metadata:
  name: carAppService
  labels:
    app: carAppService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carapp
  template:
    metadata:
      labels:
        app: carapp
    spec:
      containers:
      - name: carapp
        image: carapp:latest
        ports:
        - containerPort: 8585
